# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCatalog():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_catalog(self):
    self.driver.get("https://sokolov.ru/")
    self.driver.set_window_size(1512, 859)
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, "img:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # actions.move_to_element(element, 0, 0).perform()
    catalog_lctr = By.CSS_SELECTOR, "[class*='CatalogButton_catalog-btn_big']"
    self.driver.find_element(*catalog_lctr).click()
    self.driver.find_element(By.LINK_TEXT, "Все категории").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".TopCatalog_catalog-banner__img__cgvrE")
    actions = ActionChains(self.driver)

    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    element_locator = "css selector", 'div[data-qa="product-list"]'
    plitka_web_element = self.driver.find_elements(*element_locator)
    assert len(plitka_web_element)>0, ""
    self.driver.close()
  
